# Generated by Django 6.0.7 on 2026-08-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_remove_medicine_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinebatch',
            name='batch_number',
            field=models.PositiveIntegerField(auto_created=True),
        ),
    ]
