# Generated by Django 6.0.7 on 2026-08-16 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicine', '0003_remove_medicine_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('sale_return', 'Sale Return'), ('purchase_return', 'Purchase Return'), ('damage', 'Damage'), ('expiry', 'Expiry'), ('manual_adjustment', 'Manual Adjustment'), ('stock_transfer', 'Stock Transfer')], max_length=30)),
                ('quantity', models.PositiveIntegerField()),
                ('reference_id', models.CharField(blank=True, max_length=20, null=True)),
                ('previous_stock', models.PositiveIntegerField()),
                ('new_stock', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.medicinebatch')),
            ],
            options={
                'db_table': 'inventory_txn',
            },
        ),
    ]
