# Generated by Django 6.0.7 on 2026-08-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='emergency_contact',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Emergency Contact'),
        ),
    ]
