# Generated by Django 6.0.7 on 2026-08-09 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_id', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Pharmacy Name')),
                ('registration_number', models.PositiveIntegerField(unique=True, verbose_name='Registration Number')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email Address')),
                ('phone', models.PositiveBigIntegerField(verbose_name='Phone Number')),
                ('website', models.URLField(blank=True, max_length=100, null=True, verbose_name='Website')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('opening_time', models.TimeField(verbose_name='Opening Time')),
                ('closing_time', models.TimeField(verbose_name='Closing Time')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.district')),
            ],
            options={
                'db_table': 'pharmacy',
            },
        ),
    ]
